### ISSUE TITLE
Issue installing 3.10

### ISSUE THREAD

**Issue by dudash** [jaredhocutt/openshift-provision#2]
When trying to install a 3.10 cluster:
```TASK [install_openshift : Run OpenShift prerequisites] ****************************************************************************************************************
Monday 13 August 2018  19:10:06 +0000 (0:00:00.850)       0:24:47.446 *********
fatal: [ec2-18-222-20-123.us-east-2.compute.amazonaws.com]: FAILED! => {
    "changed": true,
    "cmd": [
        "ansible-playbook",
        "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"
    ],
    "delta": "0:00:00.695773",
    "end": "2018-08-13 19:10:07.935256",
    "rc": 1,
    "start": "2018-08-13 19:10:07.239483"
}

STDERR:

ERROR! the playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml could not be found


MSG:

non-zero return code
```

**Comment by jaredhocutt** [comment]
Thanks for giving this a try with 3.10. I haven't had a chance to see if it would work.

There are a few other 3.10 changes that will need some logic changes in the playbooks. Off the top of my head, those are:

1. Node labeling is different from 3.9 to 3.10 (i.e. `openshift_node_labels` has been removed)
2. OpenShift Container Storage (formerly CNS) 3.10 hasn't been released yet and this installer currently assumes a matching version of OCS

I'm sure this list will grow once I have a chance to go through a 3.10 install.

**Comment by jaredhocutt** [comment]
The inventory file also has the OpenShift version hard coded rather than it using the variable `{{ openshift_version }}`.

https://github.com/jaredhocutt/openshift-provision/blob/1c5f64928d8a35a6a2ce18822c9ff589ae6dd308/playbooks/roles/install_openshift/templates/hosts.multi.ini.j2#L54

Created #8 to go ahead and get this fixed.

**Comment by jaredhocutt** [comment]
I just added 3.10 support with #12 

@dudash Check it out and let me know if it fixes this.

**Comment by dudash** [comment]
trying now - will close this out if it works.

**Comment by dudash** [comment]
lgtm
