### ISSUE TITLE
Gluster Version Check Regular Expression Error

### ISSUE THREAD

**Issue by dmc5179** [jaredhocutt/openshift-provision#29]
In this file on the master:

/usr/share/ansible/openshift-ansible/roles/openshift_storage_glusterfs/tasks/version_check.yml
<pre>
TASK [openshift_storage_glusterfs : Check for specified container versions] ***************************************************************************************************************************************
Friday 22 February 2019  16:49:20 +0000 (0:00:00.198)       0:00:27.232 ******* 
fatal: [ip-172-31-235-70.ec2.internal]: FAILED! => {"changed": false, "failed": true, "msg": "A valid version tag must be specified for all GlusterFS container images.\nValid image tags take the form of \"v3.x\" where \"x\" can be a one or two release\nversions (e.g. \"v3.0\" or \"v3.0.1\"). The following image versions were detected:\n\nGlusterFS: latest\nHeketi: latest\nglusterblock-provisioner: 3.10\n"}
</pre>

This is apparently because python/ansible have some issue about regular expressions that seems to cause the variable substitution to fail. I commented out the var settings like this, where the # lines are what was there and the line below each # is what I added:

<pre>
  vars:
#    glusterfs_version: "{{ (openshift_storage_glusterfs_image | regex_replace('^.*:(v?)(?P<version>.+$)', '\\g<version>')) }}"
    glusterfs_version: "3.10"
#    heketi_version: "{{ (openshift_storage_glusterfs_heketi_image | regex_replace('^.*:(v?)(?P<version>.+$)', '\\g<version>')) }}"
    heketi_version: "3.10"
#    glusterblock_version: "{{ (openshift_storage_glusterfs_block_image | regex_replace('^.*:(v?)(?P<version>.+$)', '\\g<version>')) }}"
    glusterblock_version: "3.10"
</pre>

in the vars/aws.yml file it comes default with:
<pre>
openshift_version: "3.10"
</pre>
I just guessed to put that in. That allowed the rest of the playbooks to work. Now I can get to the openshift cluster I made on the public internet.

**Comment by jaredhocutt** [comment]
The playbooks used to kick off the OpenShift install, that ultimately end up at `/usr/share/ansible/openshift-ansible` on the master come from this repo:

https://github.com/openshift/openshift-ansible/

I'd recommend posting this issue there since I don't have any control over that repo or set of playbooks.

**Comment by dmc5179** [comment]
Thanks for pointing me to the other repository. Looks like the got rid of that file and are using something else due to that issue.

Do the owners of the openshif-ansible git repo create the AWS AMIs that are launched as part of this tool?

**Comment by jaredhocutt** [comment]
The AMI that I use is just a base RHEL 7 AMI. From there, it is subscribed to RHSM, the apprpriate repos are enabled, and then everything installed/configured from there.

In the case of these playbooks, they come from the installation of the `openshift-ansible` RPM in the `rhel-7-server-ose-{{ openshift_version }}-rpms` repo.

In general, if there's a specific release that has a fix (or maybe doesn't have a bug that was introduced), you can specify `openshift_version_minor` in your vars file for this tool and it will be sure to install that specific version of the `openshift-ansible` RPM.
