### ISSUE TITLE
Cannot install because GlusterFS install doesnt like the "latest" tag

### ISSUE THREAD

**Issue by dealyb** [jaredhocutt/openshift-provision#30]
when i run the provision, i get...
I have tried putting these in aws.yml , not sure where they should go.
Failure summary:

  1. Hosts:    ip-172-31-237-64.ec2.internal
     Play:     Configure GlusterFS
     Task:     Check for specified container versions
     Message:  A valid version tag must be specified for all GlusterFS container images.
               Valid image tags take the form of "v3.x" where "x" can be a one or two release
               versions (e.g. "v3.0" or "v3.0.1"). The following image versions were detected:
               
               GlusterFS: latest
               Heketi: latest
               glusterblock-provisioner: latest

**Comment by jaredhocutt** [comment]
There's a known issue in the latest version of OpenShift 3.11 that's causing this to happen.

I just added an item under the known issues in the README with details on how to workaround it for now: https://github.com/jaredhocutt/openshift-provision#issue-glusterfs-broken-in-latest-releases-of-openshift-311

The short version is to install OpenShift 3.11.43, which does not have the bug in it. You can do this by specifying the following in your variable file:

```yaml
openshift_version: "3.11"
openshift_version_minor: "3.11.43"
```

**Comment by dealyb** [comment]
Thank You,  this is a very useful repo by the way! I appreciate it being available and your quick response is helping me out also!  thanks.
