### ISSUE TITLE
Dependency Resolution Error for java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64

### ISSUE THREAD

**Issue by dealyb** [jaredhocutt/openshift-provision#31]
Running an install today, using OCP 3.11.43 i ran into this issue with dependency resolution that i havent seen before. BTW, I am running the provision from an aws ec2 instance

TASK [host_prep_bastion : Install OpenShift playbooks (3.10, 3.11) - minor version] ************************************************************************************************
Monday 04 March 2019  18:41:52 +0000 (0:00:00.039)       0:02:38.399 ********** 
fatal: [ec2-18-215-91-73.compute-1.amazonaws.com]: FAILED! => {
    "changed": false,
    "rc": 1,
    "results": [
        "Loaded plugins: product-id, search-disabled-repos, subscription-manager\nResolving Dependencies\n--> Running transaction check\n---> Package openshift-ansible.noarch 0:3.11.43-1.git.0.fa69a02.el7 will be installed\n--> Processing Dependency: openshift-ansible-docs = 3.11.43-1.git.0.fa69a02.el7 for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: openshift-ansible-playbooks = 3.11.43-1.git.0.fa69a02.el7 for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: openshift-ansible-roles = 3.11.43-1.git.0.fa69a02.el7 for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: ansible >= 2.5.7 for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: httpd-tools for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: java-1.8.0-openjdk-headless for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: patch for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: python-passlib for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Processing Dependency: python2-crypto for package: openshift-ansible-3.11.43-1.git.0.fa69a02.el7.noarch\n--> Running transaction check\n---> Package ansible.noarch 0:2.6.14-1.el7ae will be installed\n--> Processing Dependency: python-httplib2 for package: ansible-2.6.14-1.el7ae.noarch\n--> Processing Dependency: python-jmespath for package: ansible-2.6.14-1.el7ae.noarch\n--> Processing Dependency: python-paramiko for package: ansible-2.6.14-1.el7ae.noarch\n--> Processing Dependency: sshpass for package: ansible-2.6.14-1.el7ae.noarch\n---> Package httpd-tools.x86_64 0:2.4.6-88.el7 will be installed\n--> Processing Dependency: libapr-1.so.0()(64bit) for package: httpd-tools-2.4.6-88.el7.x86_64\n--> Processing Dependency: libaprutil-1.so.0()(64bit) for package: httpd-tools-2.4.6-88.el7.x86_64\n---> Package java-1.8.0-openjdk-headless.x86_64 1:1.8.0.201.b09-0.el7_6 will be installed\n--> Processing Dependency: copy-jdk-configs >= 3.3 for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: tzdata-java >= 2015d for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: cups-libs(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: jpackage-utils for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: libjpeg.so.62(LIBJPEG_6.2)(64bit) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: lksctp-tools(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: pcsc-lite-devel(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n--> Processing Dependency: libjpeg.so.62()(64bit) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n---> Package openshift-ansible-docs.noarch 0:3.11.43-1.git.0.fa69a02.el7 will be installed\n---> Package openshift-ansible-playbooks.noarch 0:3.11.43-1.git.0.fa69a02.el7 will be installed\n---> Package openshift-ansible-roles.noarch 0:3.11.43-1.git.0.fa69a02.el7 will be installed\n---> Package patch.x86_64 0:2.7.1-10.el7_5 will be installed\n---> Package python-passlib.noarch 0:1.6.5-2.el7 will be installed\n---> Package python2-crypto.x86_64 0:2.6.1-15.el7 will be installed\n--> Processing Dependency: libtomcrypt.so.0()(64bit) for package: python2-crypto-2.6.1-15.el7.x86_64\n--> Running transaction check\n---> Package apr.x86_64 0:1.4.8-3.el7_4.1 will be installed\n---> Package apr-util.x86_64 0:1.5.2-6.el7 will be installed\n---> Package copy-jdk-configs.noarch 0:3.3-10.el7_5 will be installed\n---> Package cups-libs.x86_64 1:1.6.3-35.el7 will be installed\n--> Processing Dependency: libavahi-client.so.3()(64bit) for package: 1:cups-libs-1.6.3-35.el7.x86_64\n--> Processing Dependency: libavahi-common.so.3()(64bit) for package: 1:cups-libs-1.6.3-35.el7.x86_64\n---> Package java-1.8.0-openjdk-headless.x86_64 1:1.8.0.201.b09-0.el7_6 will be installed\n--> Processing Dependency: pcsc-lite-devel(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n---> Package javapackages-tools.noarch 0:3.4.1-11.el7 will be installed\n--> Processing Dependency: python-javapackages = 3.4.1-11.el7 for package: javapackages-tools-3.4.1-11.el7.noarch\n---> Package libjpeg-turbo.x86_64 0:1.2.90-6.el7 will be installed\n---> Package libtomcrypt.x86_64 0:1.17-26.el7 will be installed\n--> Processing Dependency: libtommath >= 0.42.0 for package: libtomcrypt-1.17-26.el7.x86_64\n--> Processing Dependency: libtommath.so.0()(64bit) for package: libtomcrypt-1.17-26.el7.x86_64\n---> Package lksctp-tools.x86_64 0:1.0.17-2.el7 will be installed\n---> Package python-httplib2.noarch 0:0.9.2-1.el7 will be installed\n---> Package python-paramiko.noarch 0:2.1.1-9.el7 will be installed\n---> Package python2-jmespath.noarch 0:0.9.0-4.el7ae will be installed\n---> Package sshpass.x86_64 0:1.06-2.el7 will be installed\n---> Package tzdata-java.noarch 0:2018i-1.el7 will be installed\n--> Running transaction check\n---> Package avahi-libs.x86_64 0:0.6.31-19.el7 will be installed\n---> Package java-1.8.0-openjdk-headless.x86_64 1:1.8.0.201.b09-0.el7_6 will be installed\n--> Processing Dependency: pcsc-lite-devel(x86-64) for package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64\n---> Package libtommath.x86_64 0:0.42.0-6.el7 will be installed\n---> Package python-javapackages.noarch 0:3.4.1-11.el7 will be installed\n--> Finished Dependency Resolution\nError: Package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64 (rhel-7-server-rpms)\n           Requires: pcsc-lite-devel(x86-64)\n**********************************************************************\nyum can be configured to try to resolve such errors by temporarily enabling\ndisabled repos and searching for missing dependencies.\nTo enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf\n**********************************************************************\n\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"
    ]
}

MSG:

Error: Package: 1:java-1.8.0-openjdk-headless-1.8.0.201.b09-0.el7_6.x86_64 (rhel-7-server-rpms)
           Requires: pcsc-lite-devel(x86-64)

**Comment by jaredhocutt** [comment]
Good timing because I just pushed a fix for this 5 minutes ago :)

The error you're seeing is documented here: https://access.redhat.com/solutions/3949501

The current workaround is to enable the `rhel-7-server-optional-rpms` repo which I've pushed a change to. Try your run again and let me know if you still hit the issue.

**Comment by dealyb** [comment]
thanks!  that fixed it.  Thanks again for your good work here!
