### ISSUE TITLE
govcloud

### ISSUE THREAD

**Issue by danseo-reisys** [jaredhocutt/openshift-provision#39]
does this script work against govcloud regions.  
i'm getting following error...

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: AWS was not able to validate the provided access credentials

TASK [provision_aws : Create EC2 key pair] **********************************************************************************************************************************************************
task path: /app/playbooks/roles/provision_aws/tasks/keypair.yml:3
Monday 05 August 2019  21:29:28 +0000 (0:00:00.907)       0:00:01.108 *********
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470 `" && echo ansible-tmp-1565040568.495407-12950719490470="` echo /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/cloud/amazon/ec2_key.py
<localhost> PUT /root/.ansible/tmp/ansible-local-1av7_alxb/tmpot1jb820 TO /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470/ec2_key.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470/ /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470/ec2_key.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470/ec2_key.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1565040568.495407-12950719490470/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_4tgoi8dw/ansible_module_ec2_key.py", line 176, in find_key_pair
    key = ec2_client.describe_key_pairs(KeyNames=[name])['KeyPairs'][0]
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: AWS was not able to validate the provided access credentials

fatal: [localhost]: FAILED! => {
    "boto3_version": "1.9.80",
    "botocore_version": "1.12.80",
    "changed": false,
    "error": {
        "code": "AuthFailure",
        "message": "AWS was not able to validate the provided access credentials"
    },
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "ec2_url": null,
            "force": false,
            "key_material": null,
            "name": "ge1comet-reisystems-net",
            "profile": null,
            "region": "us-gov-east-1",
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "wait": false,
            "wait_timeout": "300"
        }
    },
    "response_metadata": {
        "http_headers": {
            "date": "Mon, 05 Aug 2019 21:29:28 GMT",
            "server": "AmazonEC2",
            "transfer-encoding": "chunked"
        },
        "http_status_code": 401,
        "request_id": "b06ea02e-daa1-4c51-a61b-75259b12308f",
        "retry_attempts": 0
    }
}

MSG:

error finding keypair: An error occurred (AuthFailure) when calling the DescribeKeyPairs operation: AWS was not able to validate the provided access credentials

**Comment by jaredhocutt** [comment]
It hasn't been tested against the GovCloud regions in a long time. In the past, no it has not worked in GovCloud due to a reliance on Route53, which was not available in the GovCloud regions.

However, the error you're getting is telling you that your AWS keys are incorrect and it's unable to authenticate to the AWS API.

If you do get it working in GovCloud, I'd love to know!

**Comment by danseo-reisys** [comment]
i have setup a private dns zone in govcloud.  once the cluster is setup, i was going to replicate the records on public dns with same domain.  i will try different key pair.

**Comment by danseo-reisys** [comment]
tried with different govcloud admin user key pairs.  still having the same issue.   can you try running against govcloud?  i don't think the auth works on govcloud.  

Status: Image is up to date for quay.io/jhocutt/openshift-provision:latest
ansible-playbook 2.6.6
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
Using /app/ansible.cfg as config file
 [WARNING]:  * Failed to parse /app/inventory/inventory.aws_ec2.yml with aws_ec2 plugin: Failed to describe instances: An error occurred (AuthFailure) when calling the
DescribeInstances operation: AWS was not able to validate the provided access credentials

  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 270, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 553, in parse
    results = self._query(regions, filters, strict_permissions)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 383, in _query
    return {'aws_ec2': self._get_instances_by_region(regions, filters, strict_permissions)}
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 325, in _get_instances_by_region
    raise AnsibleError("Failed to describe instances: %s" % to_native(e))

Status: Image is up to date for quay.io/jhocutt/openshift-provision:latest
ansible-playbook 2.6.6
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.6 (default, Jul 19 2018, 14:25:17) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
Using /app/ansible.cfg as config file
 [WARNING]:  * Failed to parse /app/inventory/inventory.aws_ec2.yml with aws_ec2 plugin: Failed to describe instances: An error occurred (AuthFailure) when calling the
DescribeInstances operation: AWS was not able to validate the provided access credentials

  File "/usr/local/lib/python3.6/site-packages/ansible/inventory/manager.py", line 270, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 553, in parse
    results = self._query(regions, filters, strict_permissions)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 383, in _query
    return {'aws_ec2': self._get_instances_by_region(regions, filters, strict_permissions)}
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/inventory/aws_ec2.py", line 325, in _get_instances_by_region
    raise AnsibleError("Failed to describe instances: %s" % to_native(e))

 [WARNING]:  * Failed to parse /app/inventory/inventory.aws_ec2.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory


 [WARNING]: Unable to parse /app/inventory/inventory.aws_ec2.yml as an inventory source

Parsed /app/inventory/inventory.yml inventory source with yaml plugin
statically imported: /app/playbooks/roles/provision_aws/tasks/keypair.yml
statically imported: /app/playbooks/roles/provision_aws/tasks/vpc.yml
statically imported: /app/playbooks/roles/provision_aws/tasks/security_groups.yml
statically imported: /app/playbooks/roles/provision_aws/tasks/ec2.yml
statically imported: /app/playbooks/roles/provision_aws/tasks/route53.yml
statically imported: /app/playbooks/roles/install_openshift/tasks/certs.yml

PLAYBOOK: provision.yml ***********************************************************************************************************************************************************
7 plays in playbooks/aws/provision.yml

PLAY [localhost] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************
task path: /app/playbooks/aws/provision.yml:3
Tuesday 06 August 2019  15:41:26 +0000 (0:00:00.168)       0:00:00.168 ********
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255 `" && echo ansible-tmp-1565106086.3324063-271226278212255="` echo /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/system/setup.py
<localhost> PUT /root/.ansible/tmp/ansible-local-1lm2vy86u/tmp_ntpgzow TO /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255/ /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'python /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1565106086.3324063-271226278212255/ > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

**Comment by jaredhocutt** [comment]
I don't have time to test a full GovCloud install right now, but I was able to get it to authenticate with the admin access keys.

Can you show me what your `env-file` and `vars-file` looks like? **PLEASE REMOVE ANY KEYS OR LOGIN INFO**

**Comment by neelk-s1** [comment]
I'm also experiencing this issue. I've tried multiple keys with no luck. My playbook uses EC2 just fine right before it calls Route53.

**Comment by jaredhocutt** [comment]
@neelk-s1 AWS GovCloud doesn't support public hosted zones in Route53, which is what is causing this to fail. I'd be happy to accept a PR that detects if it's in GovCloud and instead uses a private hosted zone.

**Comment by neelk-s1** [comment]
Yep, I'm aware public Route53 is unsupported. I was trying to use a private hosted zone I set up previously. I found an alternate solution that obviated Ansible.
